--- 
components: 
  schemas: 
    BenchmarkReference: 
      $ref: "models/BenchmarkReference.yaml#/components/schemas/BenchmarkReference"
    BenchmarkSnapshot:      
      $ref: "models/BenchmarkSnapshot.yaml#/components/schemas/BenchmarkSnapshot"
    EanLookup:      
      $ref: "models/EanLookup.yaml#/components/schemas/EanLookup"
info: 
  description: "Model Definitions for DVU"
  title: DVU Benchmark data models
  version: "0.1.0"
openapi: "3.0.0"


# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object
