--- 
components: 
  schemas: 
    BenchmarkReference: 
      allOf: 
        - $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/ngsi-ld.yaml#/Common"
      description: |
          This entity contains a harmonised description of a BenchmarkReference. This entity is associated with utility building categories based on BAG data, compared to the BAG data model for 'gebruiksdoelen' of 'Verblijfsobjecten', the following changes are introduced:
          - Energy usage reference data is added.
          - Construction periods are introduced, using the format of the 'oorspronkelijkBouwjaar'.
          
          ## Data Model
          For a full description of the following attributes refer to DVU [DVU documentation](https://example.com)
      properties: 
        referenceValue: 
          description: "Reference value of energy use [kWh per m2] for this buildingUsage and constructionPeriod"
          format: float
          type: number
          x-ngsi: 
            model: "https://schema.org/Number"
            type: Property
        buildingUsage:
          $ref: "https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2/openapi.yaml#/components/schemas/Gebruiksdoel"
        constructionPeriod: 
            format: array
            x-ngsi: 
              model: "https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2/openapi.yaml#/components/schemas/AdresUitgebreid/oorspronkelijkBouwjaar"
              type: Property
info: 
  description: "Model Definitions for DVU"
  title: DVU Benchmark data models
  version: "0.1.0"
openapi: "3.0.0"


# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object
