--- 
components: 
  schemas: 
    EanLookup:      
      allOf: 
        - $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/ngsi-ld.yaml#/Common"
      description: |
          This entity contains a harmonised description of a EanLookup. This entity allows reverse lookup of the 'AdresseerbaarObjecId' from the BAG, based on known EAN nummers of energy meters.
          
          ## Data Model
          For a full description of the following attributes refer to DVU [DVU documentation](https://example.com)
      properties: 
        Test:
          type: number
info: 
  description: "Model Definitions for DVU"
  title: DVU data model EanLookup
  version: "0.1.0"
openapi: "3.0.0"


# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object
